/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
package org.zeromq.czmq

import com.sun.jna.Library
import com.sun.jna.Native
import com.sun.jna.Pointer

class Zhash {

//    static {
//        Map<String, Boolean> libraries = new LinkedHashMap<>()
//        libraries.put("zmq", false)
//        libraries.put("uuid", true)
//        libraries.put("systemd", true)
//        libraries.put("lz4", true)
//        libraries.put("curl", true)
//        libraries.put("nss", true)
//        libraries.put("microhttpd", true)
//        libraries.put("czmq", false)
//        libraries.put("czmqjni", false)
//        ZmqNativeLoader.loadLibraries(libraries)
//    }

    private interface NativeLib : Library {
        fun zhash_new(): Pointer
        fun zhash_unpack(frame: Pointer): Pointer
        fun destroy(self: Pointer)
        fun zhash_insert(self: Pointer, key: String, item: Pointer): Int
        fun zhash_update(self: Pointer, key: String, item: Pointer): Unit
        fun zhash_delete(self: Pointer, key: String): Unit
        fun zhash_lookup(self: Pointer, key: String): Pointer
        fun zhash_rename(self: Pointer, oldKey: String, newKey: String): Int
        fun zhash_size(self: Pointer): Pointer
        fun zhash_dup(self: Pointer): Pointer
        fun zhash_keys(self: Pointer): Pointer
        fun zhash_first(self: Pointer): Pointer
        fun zhash_next(self: Pointer): Pointer
        fun zhash_cursor(self: Pointer): String
        fun zhash_comment(self: Pointer, format: Array<out String>): Unit
        fun zhash_pack(self: Pointer): Pointer
        fun zhash_save(self: Pointer, filename: String): Int
        fun zhash_load(self: Pointer, filename: String): Int
        fun zhash_refresh(self: Pointer): Int
        fun zhash_autofree(self: Pointer): Unit
        fun zhash_test(verbose: Boolean): Unit
    }

    companion object {
        private val nativeLib: NativeLib =
            Native.load("czmq", NativeLib::class.java)

    /**
     * Self test of this class.
     */
    fun test(verbose: Boolean): Unit {
        nativeLib.zhash_test(verbose)
    }

    }

    var self: Pointer

    /**
     * Create a new, empty hash container
     */
    constructor() {
        /*  TODO: if __new fails, self is null...            */
        self = nativeLib.zhash_new()
    }

    constructor(pointer: Pointer) {
        self = pointer
    }

    /**
     * Unpack binary frame into a new hash table. Packed data must follow format
     * defined by zhash_pack. Hash table is set to autofree. An empty frame
     * unpacks to an empty hash table.
     */
//    public static Zhash unpack (frame: Zframe) {
//        return new Zhash (nativeLib.zhash_unpack (frame.self))
//    }
//
    /**
     * Destroy a hash container and all items in it
     */
//    @Override
//    public void close () {
//        nativeLib.zhash_destroy(self)
//        self = 0
//    }
//
    /**
     * Insert item into hash table with specified key and item.
     * If key is already present returns -1 and leaves existing item unchanged
     * Returns 0 on success.
     */
    fun insert(key: String, item: Pointer): Int {
        return nativeLib.zhash_insert(self, key, item)
    }

    /**
     * Update item into hash table with specified key and item.
     * If key is already present, destroys old item and inserts new one.
     * Use free_fn method to ensure deallocator is properly called on item.
     */
    fun update(key: String, item: Pointer): Unit {
        nativeLib.zhash_update(self, key, item)
    }

    /**
     * Remove an item specified by key from the hash table. If there was no such
     * item, this function does nothing.
     */
    fun delete(key: String): Unit {
        nativeLib.zhash_delete(self, key)
    }

    /**
     * Return the item at the specified key, or null
     */
    fun lookup(key: String): Pointer {
        return nativeLib.zhash_lookup(self, key)
    }

    /**
     * Reindexes an item from an old key to a new key. If there was no such
     * item, does nothing. Returns 0 if successful, else -1.
     */
    fun rename(oldKey: String, newKey: String): Int {
        return nativeLib.zhash_rename(self, oldKey, newKey)
    }

    /**
     * Return the number of keys/items in the hash table
     */
    fun size(): Pointer {
        return nativeLib.zhash_size(self)
    }

    /**
     * Make copy of hash table; if supplied table is null, returns null.
     * Does not copy items themselves. Rebuilds new table so may be slow on
     * very large tables. NOTE: only works with item values that are strings
     * since there's no other way to know how to duplicate the item value.
     */
    fun dup(): Zhash {
        return Zhash (nativeLib.zhash_dup(self))
    }

    /**
     * Return keys for items in table
     */
    fun keys(): Zlist {
        return Zlist (nativeLib.zhash_keys(self))
    }

    /**
     * Simple iterator; returns first item in hash table, in no given order,
     * or NULL if the table is empty. This method is simpler to use than the
     * foreach() method, which is deprecated. To access the key for this item
     * use zhash_cursor(). NOTE: do NOT modify the table while iterating.
     */
    fun first(): Pointer {
        return nativeLib.zhash_first(self)
    }

    /**
     * Simple iterator; returns next item in hash table, in no given order,
     * or NULL if the last item was already returned. Use this together with
     * zhash_first() to process all items in a hash table. If you need the
     * items in sorted order, use zhash_keys() and then zlist_sort(). To
     * access the key for this item use zhash_cursor(). NOTE: do NOT modify
     * the table while iterating.
     */
    fun next(): Pointer {
        return nativeLib.zhash_next(self)
    }

    /**
     * After a successful first/next method, returns the key for the item that
     * was returned. This is a constant string that you may not modify or
     * deallocate, and which lasts as long as the item in the hash. After an
     * unsuccessful first/next, returns NULL.
     */
    fun cursor(): String {
        return nativeLib.zhash_cursor(self)
    }

    /**
     * Add a comment to hash table before saving to disk. You can add as many
     * comment lines as you like. These comment lines are discarded when loading
     * the file. If you use a null format, all comments are deleted.
     */
    fun comment(vararg format: String): Unit {
        nativeLib.zhash_comment(self, format)
    }

    /**
     * Serialize hash table to a binary frame that can be sent in a message.
     * The packed format is compatible with the 'dictionary' type defined in
     * http://rfc.zeromq.org/spec:35/FILEMQ, and implemented by zproto:
     *
     *    ; A list of name/value pairs
     *    dictionary      = dict-count *( dict-name dict-value )
     *    dict-count      = number-4
     *    dict-value      = longstr
     *    dict-name       = string
     *
     *    ; Strings are always length + text contents
     *    longstr         = number-4 *VCHAR
     *    string          = number-1 *VCHAR
     *
     *    ; Numbers are unsigned integers in network byte order
     *    number-1        = 1OCTET
     *    number-4        = 4OCTET
     *
     * Comments are not included in the packed data. Item values MUST be
     * strings.
     */
    fun pack(): Zframe {
        return Zframe (nativeLib.zhash_pack(self))
    }

    /**
     * Save hash table to a text file in name=value format. Hash values must be
     * printable strings; keys may not contain '=' character. Returns 0 if OK,
     * else -1 if a file error occurred.
     */
    fun save(filename: String): Int {
        return nativeLib.zhash_save(self, filename)
    }

    /**
     * Load hash table from a text file in name=value format; hash table must
     * already exist. Hash values must printable strings; keys may not contain
     * '=' character. Returns 0 if OK, else -1 if a file was not readable.
     */
    fun load(filename: String): Int {
        return nativeLib.zhash_load(self, filename)
    }

    /**
     * When a hash table was loaded from a file by zhash_load, this method will
     * reload the file if it has been modified since, and is "stable", i.e. not
     * still changing. Returns 0 if OK, -1 if there was an error reloading the
     * file.
     */
    fun refresh(): Int {
        return nativeLib.zhash_refresh(self)
    }

    /**
     * Set hash for automatic value destruction. Note that this assumes that
     * values are NULL-terminated strings. Do not use with different types.
     */
    fun autofree(): Unit {
        nativeLib.zhash_autofree(self)
    }

}
