/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
package org.zeromq.czmq

import com.sun.jna.Library
import com.sun.jna.Native
import com.sun.jna.Pointer

class ZhttpClient {

//    static {
//        Map<String, Boolean> libraries = new LinkedHashMap<>()
//        libraries.put("zmq", false)
//        libraries.put("uuid", true)
//        libraries.put("systemd", true)
//        libraries.put("lz4", true)
//        libraries.put("curl", true)
//        libraries.put("nss", true)
//        libraries.put("microhttpd", true)
//        libraries.put("czmq", false)
//        libraries.put("czmqjni", false)
//        ZmqNativeLoader.loadLibraries(libraries)
//    }

    private interface NativeLib : Library {
        fun zhttp_client_new(verbose: Boolean): Pointer
        fun destroy(self: Pointer)
        fun zhttp_client_test(verbose: Boolean): Unit
    }

    companion object {
        private val nativeLib: NativeLib =
            Native.load("czmq", NativeLib::class.java)

    /**
     * Self test of this class.
     */
    fun test(verbose: Boolean): Unit {
        nativeLib.zhttp_client_test(verbose)
    }

    }

    var self: Pointer

    /**
     * Create a new http client
     */
    constructor(verbose: Boolean) {
        /*  TODO: if __new fails, self is null...            */
        self = nativeLib.zhttp_client_new(verbose)
    }

    constructor(pointer: Pointer) {
        self = pointer
    }

    /**
     * Destroy an http client
     */
//    @Override
//    public void close () {
//        nativeLib.zhttp_client_destroy(self)
//        self = 0
//    }
//
}
